/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import Nivat.BiRecursion

/-!
# Coprimality tools for the bi-recursion ideals (§5, Lemma 5.2)

`Nivat.BiRecursion` needs, for `i ≠ k` and `j ≠ l`, that
`Ideal.span {S.aFac i, S.aFac k, S.cElt} = ⊤` and
`Ideal.span {S.aElt, S.cFac j, S.cFac l} = ⊤` (its theorems `aFac_aFac_cElt_span_top` and
`aElt_cFac_cFac_span_top`, owned by that file — **not** re-declared here, to avoid a duplicate
top-level declaration).  This file exports generic, `StarConfig`-independent tools towards those
two facts.

**Correction (superseding an earlier draft of this docstring):** a first attempt here tried to
avoid the paper's Hilbert-Nullstellensatz-over-`K̄` + faithfully-flat-descent route entirely, by
decomposing `S.aFac i`, `S.aFac k` into per-root linear factors and handling each pair `(λ, μ)`
via an explicit Bézout identity, dual-basis reduction and one binomial equation `w ^ D = ν`.
Reading the paper's actual proof (§5.2, Lemma 5.2, "Step 1: no common zeros", (ii)–(iii)) shows
this does not work in general: the paper's own argument does *not* decompose `c = ∏ⱼ cFac j`
factor-by-factor by root; instead, at a common zero of `a_i, a_k`, a Cramer-type integer-power
identity on `Y₁, Y₂` (using `Δ := det (v i, v k) ≠ 0`) forces `Y₁, Y₂` themselves into `ℂ^×`, and
*every* `cFac j` (for every `j`, not just `i, k`) is then transcendence-excluded from vanishing at
once.  For a general direction `vⱼ`, the exponent of the "w" variable in that factor need not
divide or relate simply to `Δ`, so there is no one-shot per-root Bézout witness of the kind
`isCoprime_linFactor_step` supplies for the single-index case `aFac_cFac_span_top`.  The
Nullstellensatz-over-`K̄` step is therefore genuinely used by the paper, not an avoidable
formalization artefact.

**What *is* avoidable**: the descent half of the paper's route.  `K̄` here is an algebraic closure
of `FF`, a *field* extension, so "ideal `= ⊤` after `⊗ K̄`" descending to "ideal `= ⊤` over `FF`"
is an elementary field-extension fact (a proper `K`-subspace stays proper after extending scalars
along a field extension, because vector spaces are free/flat over a field) — it does not need
`Mathlib.RingTheory.RingHom.FaithfullyFlat`'s general commutative-algebra machinery.

## Main results

* `span_triple_eq_top_of_isCoprime_quotient` — a generic commutative-ring reduction: three
  generators span the whole ring as soon as the first two are coprime modulo the ideal
  generated by the third.  (Still useful in principle, but not the shape the final argument for
  `aFac_aFac_cElt_span_top` takes — see the correction above.)

## Status

`span_triple_eq_top_of_isCoprime_quotient` is proved.  The Nullstellensatz-for-Laurent-rings /
descent tooling that `Nivat.BiRecursion.aFac_aFac_cElt_span_top` and `.aElt_cFac_cFac_span_top`
actually need is not yet written here; under discussion with lineG (who owns those theorems and
has independent progress on `:401`) and lineU (who owns the related Step 2/3 CRT decomposition,
which operates on the same common-zero-locus structure) to avoid duplicating effort.
-/

namespace Nivat

open AddMonoidAlgebra

variable {p m : ℕ} [Fact p.Prime] {S : StarConfig p m}

/-- If the images of `a` and `b` are coprime in `R ⧸ (c)`, then `a, b, c` together span all of
`R`.  This is the generic algebraic fact behind turning a "coprime mod the excluded locus"
statement into the `Ideal.span {_, _, _} = ⊤` shape that `Nivat.BiRecursion` needs; it has
nothing to do with `StarConfig` or Laurent polynomials. -/
theorem span_triple_eq_top_of_isCoprime_quotient {R : Type*} [CommRing R] {a b c : R}
    (h : IsCoprime (Ideal.Quotient.mk (Ideal.span {c}) a)
                    (Ideal.Quotient.mk (Ideal.span {c}) b)) :
    Ideal.span ({a, b, c} : Set R) = ⊤ := by
  obtain ⟨p, q, hpq⟩ := h
  obtain ⟨p', rfl⟩ := Ideal.Quotient.mk_surjective p
  obtain ⟨q', rfl⟩ := Ideal.Quotient.mk_surjective q
  rw [← map_mul, ← map_mul, ← map_add,
    show (1 : R ⧸ Ideal.span {c}) = Ideal.Quotient.mk (Ideal.span {c}) 1 from (map_one _).symm,
    Ideal.Quotient.mk_eq_mk_iff_sub_mem] at hpq
  obtain ⟨r, hr⟩ := Ideal.mem_span_singleton.1 hpq
  rw [Ideal.eq_top_iff_one]
  have : (1 : R) = p' * a + q' * b - c * r := by linear_combination -hr
  rw [this]
  refine Ideal.sub_mem _ (Ideal.add_mem _ ?_ ?_) ?_
  · exact Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp))
  · exact Ideal.mul_mem_left _ _ (Ideal.subset_span (by simp))
  · exact Ideal.mul_mem_right _ _ (Ideal.subset_span (by simp))

/-- Converse of `span_triple_eq_top_of_isCoprime_quotient`: if `a, b, c` together span `R`, the
images of `a` and `b` are coprime in `R ⧸ (c)`.  (Generic commutative-ring fact; the two
directions together make the reduction an iff, though we only need this direction here.) -/
theorem isCoprime_quotient_of_span_triple_eq_top {R : Type*} [CommRing R] {a b c : R}
    (h : Ideal.span ({a, b, c} : Set R) = ⊤) :
    IsCoprime (Ideal.Quotient.mk (Ideal.span {c}) a) (Ideal.Quotient.mk (Ideal.span {c}) b) := by
  refine (Ideal.sup_eq_top_iff_isCoprime _ _).1 ?_
  have hmap : Ideal.map (Ideal.Quotient.mk (Ideal.span {c})) (Ideal.span ({a, b, c} : Set R))
      = Ideal.span (Ideal.Quotient.mk (Ideal.span {c}) '' ({a, b, c} : Set R)) :=
    Ideal.map_span _ _
  rw [h, Ideal.map_top] at hmap
  have hc0 : Ideal.Quotient.mk (Ideal.span {c}) c = 0 :=
    Ideal.Quotient.eq_zero_iff_mem.2 (Ideal.subset_span rfl)
  have himg : (Ideal.Quotient.mk (Ideal.span {c}) '' ({a, b, c} : Set R))
      = ({Ideal.Quotient.mk (Ideal.span {c}) a, Ideal.Quotient.mk (Ideal.span {c}) b, 0} :
        Set (R ⧸ Ideal.span {c})) := by
    simp [Set.image_insert_eq, hc0]
  rw [himg,
    show ({Ideal.Quotient.mk (Ideal.span {c}) a, Ideal.Quotient.mk (Ideal.span {c}) b, 0} :
        Set (R ⧸ Ideal.span {c}))
      = insert (Ideal.Quotient.mk (Ideal.span {c}) a)
          (insert (Ideal.Quotient.mk (Ideal.span {c}) b) {0}) from rfl,
    Ideal.span_insert, Ideal.span_insert, Ideal.span_singleton_zero, sup_bot_eq] at hmap
  exact hmap.symm

/- TODO(lineX): ownership of the interface theorems that consume this file's lemmas
(`Nivat.BiRecursion.aFac_aFac_cElt_span_top` and `.aElt_cFac_cFac_span_top`) is settled: both
stay in `Nivat.BiRecursion`, owned by lineG, who has fully proved `aFac_aFac_cElt_span_top`
(`:904`) via a Cramer-identity + CRT + transcendence argument, without Nullstellensatz.
`isCoprime_mono_sub_mono_sub_mod_cElt` below is *not* an independent rederivation of that result:
it is a corollary, obtained by noting that a single linear factor `f_λ` of `S.aFac i` divides the
whole product, so `Ideal.span {S.aFac i, S.aFac k, S.cElt} ≤ Ideal.span {f_λ, g_μ, S.cElt}`; since
the left side is `⊤` by `aFac_aFac_cElt_span_top`, so is the right side.  This needs
`Nivat.BiRecursion.aFac_eq_prod` to not be `private` (currently pending a one-line visibility
change from lineG). -/

/-- Fixing a root `λ ∈ S.Lam i` of `S.aFac i` and a root `μ ∈ S.Lam k` of `S.aFac k`, the two
corresponding linear factors become coprime once `S.cElt` is inverted.  A corollary of
`Nivat.BiRecursion.aFac_aFac_cElt_span_top`, via divisibility (see the note above): no new
Nullstellensatz-style argument is needed here, since that theorem already supplies it. -/
theorem isCoprime_mono_sub_mono_sub_mod_cElt (S : StarConfig p m) {i k : Fin m} (hik : i ≠ k)
    {lam mu : ℂ} (hlam : lam ∈ S.Lam i) (hmu : mu ∈ S.Lam k) :
    IsCoprime
      (Ideal.Quotient.mk (Ideal.span {S.cElt})
        (mono (S.v i) - AddMonoidAlgebra.single (0 : ℤ × ℤ) (cToFF lam)))
      (Ideal.Quotient.mk (Ideal.span {S.cElt})
        (mono (S.v k) - AddMonoidAlgebra.single (0 : ℤ × ℤ) (cToFF mu))) := by
  apply isCoprime_quotient_of_span_triple_eq_top
  set fLam : LaurentTwo FF := mono (S.v i) - AddMonoidAlgebra.single (0 : ℤ × ℤ) (cToFF lam)
    with hfLam
  set gMu : LaurentTwo FF := mono (S.v k) - AddMonoidAlgebra.single (0 : ℤ × ℤ) (cToFF mu)
    with hgMu
  have hdvd_i : fLam ∣ S.aFac i := by
    rw [hfLam, S.aFac_eq_prod i]; exact Finset.dvd_prod_of_mem _ hlam
  have hdvd_k : gMu ∣ S.aFac k := by
    rw [hgMu, S.aFac_eq_prod k]; exact Finset.dvd_prod_of_mem _ hmu
  have h1 : S.aFac i ∈ Ideal.span ({fLam, gMu, S.cElt} : Set (LaurentTwo FF)) :=
    Ideal.span_mono (Set.singleton_subset_iff.2 (by simp)) (Ideal.mem_span_singleton.2 hdvd_i)
  have h2 : S.aFac k ∈ Ideal.span ({fLam, gMu, S.cElt} : Set (LaurentTwo FF)) :=
    Ideal.span_mono (Set.singleton_subset_iff.2 (by simp)) (Ideal.mem_span_singleton.2 hdvd_k)
  have h3 : S.cElt ∈ Ideal.span ({fLam, gMu, S.cElt} : Set (LaurentTwo FF)) :=
    Ideal.subset_span (by simp)
  have hle : Ideal.span ({S.aFac i, S.aFac k, S.cElt} : Set (LaurentTwo FF))
      ≤ Ideal.span ({fLam, gMu, S.cElt} : Set (LaurentTwo FF)) := by
    refine Ideal.span_le.2 ?_
    rintro x hx
    rcases hx with rfl | rfl | rfl
    · exact h1
    · exact h2
    · exact h3
  have htop : (⊤ : Ideal (LaurentTwo FF)) ≤ Ideal.span ({fLam, gMu, S.cElt} : Set (LaurentTwo FF)) :=
    S.aFac_aFac_cElt_span_top hik ▸ hle
  exact top_le_iff.1 htop

end Nivat
