/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import Nivat.ZonotopePair

/-!
# §7. Quadratic observables make up the whole linear deficit — Theorem A

Formalisation of §7 of *The Convex Nivat Conjecture* (Pan), the end of the
self-contained part of the paper.

Fix the witness `d` and the anchor `q` of Proposition 5.3 and Corollary 6.2, and put
`h(z) = ψ(z) ψ(z + d)`, `J = D h ≠ 0` of finite support.  For every `r ∈ R_Z(S)` both
`r + q` and `r + q + d` lie in `S` (Lemma 7.1), so the quadratic observable
`Φ_r = ψ(· + r + q) ψ(· + r + q + d)` is a function of the pattern on `· + S`.  These are
linearly independent modulo the affine relations `U_S` (Lemma 7.2), because a dependence would
exhibit a non-zero Laurent polynomial annihilating `J`, contradicting Lemma 1.2.  Adding the
two counts cancels `|R_Z(S)|` exactly and gives Theorem A.

## Main results

* `Nivat.StarConfig.mem_of_mem_RZ_witness` — **Lemma 7.1**.
* `Nivat.StarConfig.quadObs_linearIndependent` — **Lemma 7.2**.
* `Nivat.StarConfig.P_ge` — **Theorem 7.3 = Theorem A**.

## Status

Complete; no `sorry`.
-/

namespace Nivat

open Finset
open scoped Pointwise

/-- A subspace generated by functions of the anchor that factor through the pattern in the
window `W` consists entirely of such functions. -/
private theorem factors_span {α : Type*} {θ : Config α} {W : Finset (ℤ × ℤ)}
    {G : Set ((ℤ × ℤ) → ℚ)}
    (hG : ∀ g ∈ G, ∀ u u' : ℤ × ℤ, pattern θ W u = pattern θ W u' → g u = g u')
    {h : (ℤ × ℤ) → ℚ} (hh : h ∈ Submodule.span ℚ G) :
    ∀ u u' : ℤ × ℤ, pattern θ W u = pattern θ W u' → h u = h u' := by
  induction hh using Submodule.span_induction with
  | mem g hg => exact hG g hg
  | zero => intro _ _ _; rfl
  | add a b _ _ ha hb =>
      intro u u' huu
      show a u + b u = a u' + b u'
      rw [ha u u' huu, hb u u' huu]
  | smul c a _ ha =>
      intro u u' huu
      show c * a u = c * a u'
      rw [ha u u' huu]

/-- The counting step of Remark 2.6, isolated from `finrank_US_le_P` so that it applies to the
enlarged space `V` of §7 as well as to `U_S`: a space of functions of the anchor that factor
through the pattern embeds into the functions on patterns, of which there are `P_θ(W)`. -/
private theorem finrank_le_P_of_factors {α : Type*} [Finite α] (θ : Config α)
    (W : Finset (ℤ × ℤ)) (V : Submodule ℚ ((ℤ × ℤ) → ℚ))
    (hfac : ∀ h ∈ V, ∀ u u' : ℤ × ℤ, pattern θ W u = pattern θ W u' → h u = h u') :
    Module.finrank ℚ V ≤ P θ W := by
  classical
  have : Fintype ↥(patterns θ W) := (patterns_finite θ W).fintype
  have hcard : Fintype.card ↥(patterns θ W) = P θ W := by
    rw [P, ← Nat.card_coe_set_eq, Nat.card_eq_fintype_card]
  have hex : ∀ π : ↥(patterns θ W), ∃ u : ℤ × ℤ, pattern θ W u = ↑π := fun π => π.2
  choose rho hrho using hex
  have hle : Module.finrank ℚ ↥V ≤ Module.finrank ℚ (↥(patterns θ W) → ℚ) := by
    refine LinearMap.finrank_le_finrank_of_injective
      (f := (⟨⟨fun x : ↥V => fun π => (x : (ℤ × ℤ) → ℚ) (rho π), fun _ _ => rfl⟩,
        fun _ _ => rfl⟩ : ↥V →ₗ[ℚ] (↥(patterns θ W) → ℚ))) ?_
    intro x y hxy
    refine Subtype.ext (funext fun u => ?_)
    have hmem : pattern θ W u ∈ patterns θ W := ⟨u, rfl⟩
    have h1 : (x : (ℤ × ℤ) → ℚ) (rho ⟨_, hmem⟩) = (y : (ℤ × ℤ) → ℚ) (rho ⟨_, hmem⟩) :=
      congrFun hxy ⟨_, hmem⟩
    rw [← hfac _ x.2 (rho ⟨_, hmem⟩) u (hrho ⟨_, hmem⟩),
      ← hfac _ y.2 (rho ⟨_, hmem⟩) u (hrho ⟨_, hmem⟩), h1]
  rwa [Module.finrank_fintype_fun_eq_card, hcard] at hle

namespace StarConfig

variable {p m : ℕ} [Fact p.Prime] (S : StarConfig p m)

/-- **Lemma 7.1.**  If `r + Z ⊆ Conv(S)` and `q, q + d ∈ Z ∩ ℤ²`, then `r + q` and
`r + q + d` lie in `S`. -/
theorem mem_of_mem_RZ_witness {W : Finset (ℤ × ℤ)} (hW : LatticeConvex W) {d q : ℤ × ℤ}
    (hq : q ∈ latticePts S.Zono) (hqd : q + d ∈ latticePts S.Zono)
    {r : ℤ × ℤ} (hr : r ∈ RZ S.Zono W) : r + q ∈ W ∧ r + q + d ∈ W := by
  refine ⟨S.mem_of_mem_RZ_Zono hW hr hq, ?_⟩
  have h := S.mem_of_mem_RZ_Zono hW hr hqd
  rwa [show r + (q + d) = r + q + d by abel] at h

/-- The quadratic scalar observable `Φ_r(u) = ψ(u + r + q) ψ(u + r + q + d)`, a function of the
anchor `u` that factors through the pattern of `θ` on `u + S`.  Paper §7. -/
noncomputable def quadObs (d q r : ℤ × ℤ) : (ℤ × ℤ) → ℚ :=
  fun u => (S.enc (S.θ (u + r + q)) : ℚ) * (S.enc (S.θ (u + r + q + d)) : ℚ)

/-- `Φ_r` is a local function of `θ` with window `S`, once `r ∈ R_Z(S)`.  Paper §7. -/
theorem isLocal_quadObs {W : Finset (ℤ × ℤ)} (hW : LatticeConvex W) {d q : ℤ × ℤ}
    (hq : q ∈ latticePts S.Zono) (hqd : q + d ∈ latticePts S.Zono)
    {r : ℤ × ℤ} (hr : r ∈ RZ S.Zono W) : IsLocal S.θ W (S.quadObs d q r) := by
  obtain ⟨h1, h2⟩ := S.mem_of_mem_RZ_witness hW hq hqd hr
  refine ⟨fun g => ((S.enc (g ⟨r + q, h1⟩) : ℤ) : ℚ) * ((S.enc (g ⟨r + q + d, h2⟩) : ℤ) : ℚ),
    fun u => ?_⟩
  show ((S.enc (S.θ (u + r + q)) : ℤ) : ℚ) * ((S.enc (S.θ (u + r + q + d)) : ℤ) : ℚ)
      = ((S.enc (S.θ (u + (r + q))) : ℤ) : ℚ) * ((S.enc (S.θ (u + (r + q + d))) : ℤ) : ℚ)
  rw [show u + (r + q) = u + r + q by abel, show u + (r + q + d) = u + r + q + d by abel]

/-- Every element of `U_S` depends on the anchor only through the pattern in the window.
This is the factorisation step inside `finrank_US_le_P`, exported for use on `V`. -/
theorem US_factors_pattern (W : Finset (ℤ × ℤ)) {h : (ℤ × ℤ) → ℚ} (hh : h ∈ S.US W)
    (u u' : ℤ × ℤ) (huu : pattern S.θ W u = pattern S.θ W u') : h u = h u' := by
  rw [US] at hh
  refine factors_span (fun g hg => ?_) hh u u' huu
  rcases hg with rfl | ⟨s, hs, rfl⟩
  · intro _ _ _; rfl
  · intro a b hab
    have h : S.θ (a + s) = S.θ (b + s) := congrFun hab ⟨s, Finset.mem_coe.mp hs⟩
    show ((S.enc (S.θ (a + s)) : ℤ) : ℚ) = ((S.enc (S.θ (b + s)) : ℤ) : ℚ)
    rw [h]

/-- Under hypothesis (1.1) the difference operator `D` annihilates every element of `U_S`.

`U_S` is spanned by the constant `1`, which the single factor `T^{H₁} - 1` of `D` already
kills, and by the translates `T^s ψ` of the encoded configuration, which `D` kills by
`act_Dop_psi`.  The statement is about the complexification, since `D` has complex
coefficients while `U_S` is a space of rational-valued functions. -/
theorem act_Dop_of_mem_US (h11 : S.CaseTwo) (W : Finset (ℤ × ℤ)) {φ : (ℤ × ℤ) → ℚ}
    (hφ : φ ∈ S.US W) : act S.Dop (fun u => ((φ u : ℚ) : ℂ)) = 0 := by
  rw [US] at hφ
  induction hφ using Submodule.span_induction with
  | mem g hg =>
      rcases hg with rfl | ⟨s, _, rfl⟩
      · show act S.Dop (fun _ : ℤ × ℤ => ((1 : ℚ) : ℂ)) = 0
        have hper : S.H S.idx₀ ∈ Per (fun _ : ℤ × ℤ => ((1 : ℚ) : ℂ)) := mem_Per_iff.mpr rfl
        rw [S.Dop_eq_mul S.idx₀, act_mul,
          (act_mono_sub_one_eq_zero_iff _ _).mpr (act_mem_Per hper)]
      · show act S.Dop (fun u : ℤ × ℤ => (((S.enc (S.θ (u + s)) : ℤ) : ℚ) : ℂ)) = 0
        have he : (fun u : ℤ × ℤ => (((S.enc (S.θ (u + s)) : ℤ) : ℚ) : ℂ)) = T s S.psi := by
          funext u
          show ((((S.enc (S.θ (u + s)) : ℤ) : ℚ) : ℂ)) = ((S.enc (S.θ (u + s)) : ℤ) : ℂ)
          push_cast
          all_goals ring
        rw [he, act_T, S.act_Dop_psi h11]
        all_goals rfl
  | zero =>
      have he : (fun u : ℤ × ℤ => (((0 : (ℤ × ℤ) → ℚ) u : ℚ) : ℂ)) = 0 := by
        funext u; simp
      rw [he, act_zero_right]
  | add a b _ _ ha hb =>
      have he : (fun u : ℤ × ℤ => (((a + b) u : ℚ) : ℂ))
          = (fun u : ℤ × ℤ => ((a u : ℚ) : ℂ)) + fun u : ℤ × ℤ => ((b u : ℚ) : ℂ) := by
        funext u
        show (((a u + b u : ℚ) : ℂ)) = ((a u : ℚ) : ℂ) + ((b u : ℚ) : ℂ)
        push_cast
        all_goals ring
      rw [he, act_add_right, ha, hb, add_zero]
  | smul c a _ ha =>
      have he : (fun u : ℤ × ℤ => (((c • a) u : ℚ) : ℂ))
          = fun u : ℤ × ℤ => ((c : ℚ) : ℂ) * ((a u : ℚ) : ℂ) := by
        funext u
        show (((c * a u : ℚ) : ℂ)) = ((c : ℚ) : ℂ) * ((a u : ℚ) : ℂ)
        push_cast
        all_goals ring
      rw [he, act_const_mul, ha]
      funext u
      show ((c : ℚ) : ℂ) * (0 : Config ℂ) u = (0 : Config ℂ) u
      simp

set_option linter.unusedVariables false in
/-- **Lemma 7.2.**  The family `{Φ_r}_{r ∈ R_Z(S)}` is linearly independent in
`{S-patterns → ℚ} / U_S`.

A dependence `∑ c_r Φ_r ∈ U_S` is killed by `D`, by `act_Dop_of_mem_US`.  But
`Φ_r = T^{r + q} h` with `h(z) = ψ(z) ψ(z + d)`, and `D` commutes with translation, so the
same computation gives `F(T) J(d, ·) = 0` for the Laurent polynomial
`F = ∑_r c_r T^{r + q}`.  The exponents `r + q` are distinct, so `F ≠ 0` as soon as some
`c_r ≠ 0`, and Lemma 1.2 (`act_ne_zero`) forbids a non-zero Laurent polynomial from
annihilating the non-zero finitely supported `J(d, ·)`.

Neither the convexity of the window nor `d ≠ 0` is used: only `J(d, ·) ≠ 0`. -/
theorem quadObs_linearIndependent (h11 : S.CaseTwo) {W : Finset (ℤ × ℤ)}
    (hW : LatticeConvex W) {d q : ℤ × ℤ} (hd : d ≠ 0) (hJ : S.Jfun d ≠ 0)
    (hq : q ∈ latticePts S.Zono) (hqd : q + d ∈ latticePts S.Zono) :
    LinearIndependent ℚ fun r : RZ S.Zono W =>
      (S.US W).mkQ (S.quadObs d q (r : ℤ × ℤ)) := by
  classical
  rw [linearIndependent_iff']
  intro s c hsum r₀ hr₀
  by_contra hc0
  -- The dependence itself lies in `U_S`.
  have hmem : (∑ r ∈ s, c r • S.quadObs d q (r : ℤ × ℤ)) ∈ S.US W := by
    have h0 : (S.US W).mkQ (∑ r ∈ s, c r • S.quadObs d q (r : ℤ × ℤ)) = 0 := by
      rw [map_sum]
      refine Eq.trans (Finset.sum_congr rfl fun r _ => ?_) hsum
      exact map_smul (S.US W).mkQ (c r) _
    rwa [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero] at h0
  have hD := S.act_Dop_of_mem_US h11 W hmem
  -- Each `Φ_r` is the translate `T^{r + q} h` of `h(z) = ψ(z) ψ(z + d)`.
  have hstep : ∀ r u : ℤ × ℤ, ((S.quadObs d q r u : ℚ) : ℂ)
      = (fun z => S.psi z * S.psi (z + d)) (u + (r + q)) := by
    intro r u
    show ((((S.enc (S.θ (u + r + q)) : ℤ) : ℚ)
        * ((S.enc (S.θ (u + r + q + d)) : ℤ) : ℚ) : ℚ) : ℂ)
      = S.psi (u + (r + q)) * S.psi (u + (r + q) + d)
    rw [show u + (r + q) = u + r + q by abel]
    show _ = ((S.enc (S.θ (u + r + q)) : ℤ) : ℂ) * ((S.enc (S.θ (u + r + q + d)) : ℤ) : ℂ)
    push_cast
    all_goals ring
  have hfun : (fun u : ℤ × ℤ => (((∑ r ∈ s, c r • S.quadObs d q (r : ℤ × ℤ)) u : ℚ) : ℂ))
      = ∑ r ∈ s, fun u : ℤ × ℤ =>
          ((c r : ℚ) : ℂ) * T ((r : ℤ × ℤ) + q) (fun z => S.psi z * S.psi (z + d)) u := by
    funext u
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul]
    push_cast
    refine Finset.sum_congr rfl fun r _ => ?_
    rw [hstep]
    all_goals rfl
  rw [hfun, act_sum_right] at hD
  -- `D` commutes with translation, so the dependence becomes one among translates of `J`.
  have hterm : ∀ r ∈ s, act S.Dop (fun u : ℤ × ℤ =>
      ((c r : ℚ) : ℂ) * T ((r : ℤ × ℤ) + q) (fun z => S.psi z * S.psi (z + d)) u)
      = fun u : ℤ × ℤ => ((c r : ℚ) : ℂ) * S.Jfun d (u + ((r : ℤ × ℤ) + q)) := by
    intro r _
    rw [act_const_mul, act_T]
    all_goals rfl
  rw [Finset.sum_congr rfl hterm] at hD
  -- Package the coefficients as a Laurent polynomial annihilating `J(d, ·)`.
  obtain ⟨F, hFdef⟩ : ∃ F : LaurentTwo ℂ,
      F = ∑ r ∈ s, AddMonoidAlgebra.single ((r : ℤ × ℤ) + q) ((c r : ℚ) : ℂ) := ⟨_, rfl⟩
  have hFJ : act F (S.Jfun d) = 0 := by
    funext z
    show act F (S.Jfun d) z = 0
    have h1 : ∑ r ∈ s, ((c r : ℚ) : ℂ) * S.Jfun d (z + ((r : ℤ × ℤ) + q)) = 0 := by
      have h2 := congrFun hD z
      simp only [Finset.sum_apply, Pi.zero_apply] at h2
      exact h2
    rw [hFdef, act_sum_apply]
    refine Eq.trans (Finset.sum_congr rfl fun r _ => ?_) h1
    exact act_single _ _ _ _
  -- The exponents `r + q` are pairwise distinct, so `F` has `c r₀ ≠ 0` as a coefficient.
  have hcoeffsum : ∀ (t : Finset (RZ S.Zono W)) (x : ℤ × ℤ),
      (∑ r ∈ t, AddMonoidAlgebra.single ((r : ℤ × ℤ) + q) ((c r : ℚ) : ℂ)
          : LaurentTwo ℂ).coeff x
        = ∑ r ∈ t, (if (r : ℤ × ℤ) + q = x then ((c r : ℚ) : ℂ) else 0) := by
    intro t x
    induction t using Finset.cons_induction with
    | empty => simp
    | cons a t ha ih =>
        rw [Finset.sum_cons, Finset.sum_cons, AddMonoidAlgebra.coeff_add, Finsupp.add_apply, ih,
          AddMonoidAlgebra.coeff_single, Finsupp.single_apply]
  have hcoeff : F.coeff ((r₀ : ℤ × ℤ) + q) = ((c r₀ : ℚ) : ℂ) := by
    rw [hFdef, hcoeffsum]
    rw [Finset.sum_eq_single_of_mem r₀ hr₀ ?_, if_pos rfl]
    intro r _ hne
    refine if_neg fun hx => hne (Subtype.ext (add_right_cancel hx))
  have hFne : F ≠ 0 := by
    intro h0
    rw [h0, AddMonoidAlgebra.coeff_zero] at hcoeff
    simp only [Finsupp.coe_zero, Pi.zero_apply] at hcoeff
    exact hc0 (by exact_mod_cast hcoeff.symm)
  exact act_ne_zero hFne (S.Jfun_finite_support d) hJ hFJ

/-- The space `V = U_S + span_ℚ {Φ_r : r ∈ R_Z(S)}` of the proof of Theorem 7.3. -/
noncomputable def VS (d q : ℤ × ℤ) (W : Finset (ℤ × ℤ)) : Submodule ℚ ((ℤ × ℤ) → ℚ) :=
  S.US W ⊔ Submodule.span ℚ (Set.range fun r : RZ S.Zono W => S.quadObs d q (r : ℤ × ℤ))

set_option linter.unusedVariables false in
/-- By Lemma 7.2, `dim V ≥ dim U_S + |R_Z(S)|`.

Only this inequality is used: Theorem 7.3 bounds `dim V` from below and `P_θ(S)` from above,
so the reverse inequality — true, since `V` is generated over `U_S` by `|R_Z(S)|` elements —
plays no role.  (The skeleton stated this as an equality.)

The proof is the dimension formula for a sum of subspaces: Lemma 7.2 says that the span `B` of
the quadratic observables meets `U_S` only in `0` and that the observables are themselves
independent, so `dim (U_S + B) = dim U_S + dim B = dim U_S + |R_Z(S)|`. -/
theorem finrank_US_add_ncard_RZ_le_finrank_VS (h11 : S.CaseTwo) {W : Finset (ℤ × ℤ)}
    (hW : LatticeConvex W) {d q : ℤ × ℤ} (hd : d ≠ 0) (hJ : S.Jfun d ≠ 0)
    (hq : q ∈ latticePts S.Zono) (hqd : q + d ∈ latticePts S.Zono) :
    Module.finrank ℚ (S.US W) + (RZ S.Zono W).ncard ≤ Module.finrank ℚ (S.VS d q W) := by
  classical
  have hRZfin : (RZ S.Zono W).Finite :=
    RZ_finite S.Zono (zero_mem_zonotope S.specDeg S.v) W
  have : Fintype ↥(RZ S.Zono W) := hRZfin.fintype
  have hli := S.quadObs_linearIndependent h11 hW hd hJ hq hqd
  have hli' : LinearIndependent ℚ fun r : RZ S.Zono W => S.quadObs d q (r : ℤ × ℤ) :=
    hli.of_comp (S.US W).mkQ
  have : FiniteDimensional ℚ ↥(S.US W) := by
    rw [US]
    exact FiniteDimensional.span_of_finite ℚ ((W.finite_toSet.image _).insert _)
  have : FiniteDimensional ℚ
      ↥(Submodule.span ℚ (Set.range fun r : RZ S.Zono W => S.quadObs d q (r : ℤ × ℤ))) :=
    FiniteDimensional.span_of_finite ℚ (Set.finite_range _)
  -- Lemma 7.2 says exactly that `U_S` meets the span of the observables only in `0`.
  have hdisj : S.US W ⊓
      Submodule.span ℚ (Set.range fun r : RZ S.Zono W => S.quadObs d q (r : ℤ × ℤ)) = ⊥ := by
    refine le_antisymm (fun x hx => ?_) bot_le
    obtain ⟨hxU, hxB⟩ := Submodule.mem_inf.mp hx
    obtain ⟨g, rfl⟩ := (Submodule.mem_span_range_iff_exists_fun ℚ).mp hxB
    have h0 : ∑ i, g i • (S.US W).mkQ (S.quadObs d q (i : ℤ × ℤ)) = 0 := by
      have hx0 : (S.US W).mkQ (∑ i, g i • S.quadObs d q (i : ℤ × ℤ)) = 0 := by
        rw [Submodule.mkQ_apply, Submodule.Quotient.mk_eq_zero]
        exact hxU
      rw [map_sum] at hx0
      simpa only [map_smul] using hx0
    have hg := Fintype.linearIndependent_iff.mp hli g h0
    simp [hg]
  have hcard : Fintype.card ↥(RZ S.Zono W) = (RZ S.Zono W).ncard := by
    rw [← Nat.card_coe_set_eq, Nat.card_eq_fintype_card]
  have hb : Module.finrank ℚ (⊥ : Submodule ℚ ((ℤ × ℤ) → ℚ)) = 0 := finrank_bot _ _
  have hsup := Submodule.finrank_sup_add_finrank_inf_eq (S.US W)
    (Submodule.span ℚ (Set.range fun r : RZ S.Zono W => S.quadObs d q (r : ℤ × ℤ)))
  rw [hdisj, hb, finrank_span_eq_card hli', hcard] at hsup
  rw [VS]
  omega

/-- `V` is a space of functions on the finite set of `S`-patterns, so `dim V ≤ P_θ(S)`. -/
theorem finrank_VS_le_P {W : Finset (ℤ × ℤ)} (hW : LatticeConvex W) {d q : ℤ × ℤ}
    (hq : q ∈ latticePts S.Zono) (hqd : q + d ∈ latticePts S.Zono) :
    Module.finrank ℚ (S.VS d q W) ≤ P S.θ W := by
  refine finrank_le_P_of_factors S.θ W _ fun h hh u u' huu => ?_
  rw [VS, US, ← Submodule.span_union] at hh
  refine factors_span (fun g hg => ?_) hh u u' huu
  rcases hg with hg | hg
  · rcases hg with rfl | ⟨s, hs, rfl⟩
    · intro _ _ _; rfl
    · intro a b hab
      have h : S.θ (a + s) = S.θ (b + s) := congrFun hab ⟨s, Finset.mem_coe.mp hs⟩
      show ((S.enc (S.θ (a + s)) : ℤ) : ℚ) = ((S.enc (S.θ (b + s)) : ℤ) : ℚ)
      rw [h]
  · obtain ⟨r, rfl⟩ := hg
    obtain ⟨F, hF⟩ := S.isLocal_quadObs hW hq hqd r.2
    intro a b hab
    show S.quadObs d q (r : ℤ × ℤ) a = S.quadObs d q (r : ℤ × ℤ) b
    rw [hF a, hF b, hab]

set_option linter.unusedVariables false in
/-- The second case of the dichotomy: under hypothesis (1.1), Theorem A holds.

The window need not be non-empty here: Lemma 2.5 holds for every window, and the two
appearances of `|R_Z(S)|` cancel whatever its value. -/
theorem P_ge_of_caseTwo (h11 : S.CaseTwo) {W : Finset (ℤ × ℤ)} (hne : W.Nonempty)
    (hW : LatticeConvex W) : W.card + 1 ≤ P S.θ W := by
  obtain ⟨d, q, hd, hJ, hq, hqd⟩ := S.exists_witness_pair h11
  have h1 := S.card_add_one_le_finrank_US_add_ncard_RZ W
  have h2 := S.finrank_US_add_ncard_RZ_le_finrank_VS h11 hW hd hJ hq hqd
  have h3 := S.finrank_VS_le_P hW hq hqd
  omega

/-- **Theorem 7.3 (Theorem A).**  Let `θ` be a star configuration and let `S ⊆ ℤ²` be
non-empty, finite and lattice-convex.  Then `P_θ(S) ≥ |S| + 1`. -/
theorem P_ge {W : Finset (ℤ × ℤ)} (hne : W.Nonempty) (hW : LatticeConvex W) :
    W.card + 1 ≤ P S.θ W := by
  by_cases h11 : S.CaseTwo
  · exact S.P_ge_of_caseTwo h11 hne hW
  · obtain ⟨a, ha⟩ := not_forall.mp h11
    exact S.P_ge_of_Dop_ind_ne_zero ha hne

/-!
**Remark 7.4 (The balance).**  The zonotope `Z` enters the proof twice and with opposite
signs: it is the cost of the affine relations, Lemma 2.5 subtracting `|R_Z(S)|`, and it is the
capacity of the quadratic witness, Lemma 7.1 supplying exactly `|R_Z(S)|` positions.  The two
cancel exactly, independently of the shape of `S` and of the size of `Z`.
-/

end StarConfig

/-- **Theorem A.**  A star configuration has `P_θ(S) ≥ |S| + 1` on every non-empty finite
lattice-convex window. -/
theorem star_complexity_lower_bound {p m : ℕ} [Fact p.Prime] (S : StarConfig p m)
    {W : Finset (ℤ × ℤ)} (hne : W.Nonempty) (hW : LatticeConvex W) :
    W.card + 1 ≤ P S.θ W := S.P_ge hne hW

end Nivat
