/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import Nivat.BiRecursion
import Nivat.Lattice.Unimodular

/-!
# §6. Putting two points into one integral zonotope

Formalisation of §6 of *The Convex Nivat Conjecture* (Pan).

Lemma 6.1 — `(Z - Z) ∩ ℤ² = (Z ∩ ℤ²) - (Z ∩ ℤ²)` for a two-dimensional zonotope generated by
lattice vectors — is proved in `Nivat.Lattice.Unimodular` (line B).  Here it is applied to the
witness `d` of Proposition 5.3, producing a single anchor `q` with both `q` and `q + d` lattice
points of `Z` (Corollary 6.2).

## Main results

* `Nivat.StarConfig.lattice_sub_Zono` — **Lemma 6.1** for `Z = Newt(A)`.
* `Nivat.StarConfig.exists_witness_pair` — **Corollary 6.2**.

## Status

Complete; no `sorry`.
-/

namespace Nivat

open scoped Pointwise

namespace StarConfig

variable {p m : ℕ} [Fact p.Prime] (S : StarConfig p m)

/-- **Lemma 6.1** applied to `Z = Newt(A) = ∑ᵢ [0, dᵢ vᵢ]`: the hypotheses `dᵢ ≥ 1`, `m ≥ 2`
and `v₁ ∦ v₂` hold by `specDeg_pos`, `two_le` and `nonparallel`. -/
theorem lattice_sub_Zono {z : ℤ × ℤ} (hz : z ∈ S.ZsubZ) :
    ∃ q₀ q₁ : ℤ × ℤ, q₀ ∈ latticePts S.Zono ∧ q₁ ∈ latticePts S.Zono ∧ z = q₁ - q₀ := by
  have hz' : toReal z ∈ zonotope S.specDeg S.v - zonotope S.specDeg S.v := hz
  exact lattice_sub_zonotope S.specDeg_pos S.two_le
    (S.nonparallel S.idx₀ S.idx₁ S.idx₀_ne_idx₁) z hz'

/-- **Corollary 6.2.**  The witness `d` of Proposition 5.3 can be written `d = q₁ - q₀` with
`q₀, q₁ ∈ Z ∩ ℤ²`; putting `q = q₀`, both `q` and `q + d` lie in `Z ∩ ℤ²`. -/
theorem exists_witness_pair (h11 : S.CaseTwo) :
    ∃ d q : ℤ × ℤ, d ≠ 0 ∧ S.Jfun d ≠ 0 ∧
      q ∈ latticePts S.Zono ∧ q + d ∈ latticePts S.Zono := by
  obtain ⟨d, hdZ, hd0, hdJ⟩ := S.exists_witness h11
  obtain ⟨q₀, q₁, hq₀, hq₁, hd⟩ := S.lattice_sub_Zono hdZ
  refine ⟨d, q₀, hd0, hdJ, hq₀, ?_⟩
  rw [hd, show q₀ + (q₁ - q₀) = q₁ by abel]
  exact hq₁

end StarConfig

end Nivat
