/-
Copyright (c) 2026. Released under Apache 2.0 license.
-/
import Nivat.Lattice.Zonotope

/-!
# Lattice points of `Z - Z`

Formalisation of **Lemma 6.1** of *The Convex Nivat Conjecture* (Pan):

> For `Z = ∑ᵢ₌₁ᵐ [0, dᵢ vᵢ]` with `dᵢ ≥ 1`, `m ≥ 2` and `v₁ ∦ v₂`,
> `(Z - Z) ∩ ℤ² = (Z ∩ ℤ²) - (Z ∩ ℤ²)`.

The paper's proof goes through a unimodular triangulation of the lattice polygon `Z`.  That
detour is not needed: the zonotope structure gives the decomposition directly.  Writing a
lattice point of `Z - Z` as `∑ᵢ (sᵢ - tᵢ) dᵢ vᵢ` with `sᵢ, tᵢ ∈ [0, 1]`, put

`q₁ = ∑_{i : tᵢ ≤ sᵢ} dᵢ vᵢ`,    `q₀ = q₁ - z`.

Then `q₁ ∈ Z ∩ ℤ²` because its coefficients are `0` or `1`, and `q₀ ∈ Z` because its `i`-th
coefficient is `1 - (sᵢ - tᵢ) ∈ [0, 1]` when `tᵢ ≤ sᵢ` and `tᵢ - sᵢ ∈ [0, 1]` otherwise;
`q₀` is a lattice point because `q₁` and `z` are.  Note that the two halves are made integral
by *choosing the coefficients of `q₁` in `{0, 1}`*, not by rounding `sᵢ - tᵢ`.

Consequently neither `m ≥ 2`, nor `v₁ ∦ v₂`, nor `dᵢ ≥ 1` is used; the argument works in any
dimension.  The hypotheses are kept because the statement is frozen and they are what the
call sites of §6 supply.

## Main results

* `Nivat.lattice_sub_zonotope` — **Lemma 6.1**.
* `Nivat.sub_lattice_subset` — the easy inclusion.
* `Nivat.zonotope_centrally_symmetric` — `c₀ - Z = Z`.

The general unimodular triangulation input the paper uses (`exists_unimodular_triangle`) is
not formalised: this project takes the zonotope-induction shortcut above instead, which does
not need it.

## Status

`lattice_sub_zonotope`, `sub_lattice_subset` and `zonotope_centrally_symmetric` are proved;
no `sorry`.
-/

namespace Nivat

open scoped Pointwise

variable {m : ℕ}

set_option linter.unusedVariables false in
/-- **Lemma 6.1.**  For a zonotope generated by positive multiples of lattice vectors, at
least two of which are non-parallel, every lattice point of `Z - Z` is a difference of two
lattice points of `Z`.

The proof does not use the unimodular triangulation of the paper, nor any of the hypotheses
`hd`, `hm`, `hij`: see the module docstring.  The hypotheses are kept because the statement is
frozen, whence the disabled linter. -/
theorem lattice_sub_zonotope {d : Fin m → ℕ} {v : Fin m → ℤ × ℤ} (hd : ∀ i, 0 < d i)
    (hm : 2 ≤ m) {i₀ j₀ : Fin m} (hij : det (v i₀) (v j₀) ≠ 0) (z : ℤ × ℤ)
    (hz : toReal z ∈ zonotope d v - zonotope d v) :
    ∃ q₀ q₁ : ℤ × ℤ, q₀ ∈ latticePts (zonotope d v) ∧ q₁ ∈ latticePts (zonotope d v) ∧
      z = q₁ - q₀ := by
  classical
  obtain ⟨x, hx, y, hy, hxy⟩ := Set.mem_sub.1 hz
  obtain ⟨s, hs, hxs⟩ := mem_zonotope_iff.1 hx
  obtain ⟨t, ht, hyt⟩ := mem_zonotope_iff.1 hy
  -- `z = ∑ᵢ (sᵢ - tᵢ) dᵢ vᵢ`, with every `sᵢ - tᵢ ∈ [-1, 1]`.
  have hzsum : toReal z = ∑ i, (s i - t i) • toReal ((d i : ℤ) • v i) := by
    rw [← hxy, ← hxs, ← hyt, ← Finset.sum_sub_distrib]
    exact Finset.sum_congr rfl fun i _ => by rw [sub_smul]
  -- `q₁` collects the generators along which `z` moves forward.
  set q₁ : ℤ × ℤ := ∑ i, if t i ≤ s i then (d i : ℤ) • v i else 0 with hq₁
  have hq₁real :
      toReal q₁ = ∑ i, (if t i ≤ s i then (1 : ℝ) else 0) • toReal ((d i : ℤ) • v i) := by
    rw [hq₁, toReal_sum]
    refine Finset.sum_congr rfl fun i _ => ?_
    by_cases h : t i ≤ s i <;> simp [h]
  refine ⟨q₁ - z, q₁, ?_, ?_, by abel⟩
  · -- `q₀ = q₁ - z` is a lattice point of `Z`: its `i`-th coefficient is
    -- `1 - (sᵢ - tᵢ)` or `tᵢ - sᵢ`, both in `[0, 1]`.
    refine mem_zonotope_iff.2
      ⟨fun i => (if t i ≤ s i then (1 : ℝ) else 0) - (s i - t i), fun i => ?_, ?_⟩
    · obtain ⟨hs0, hs1⟩ := Set.mem_Icc.1 (hs i)
      obtain ⟨ht0, ht1⟩ := Set.mem_Icc.1 (ht i)
      rw [Set.mem_Icc]
      by_cases h : t i ≤ s i
      · simp only [h, if_true]
        constructor <;> linarith
      · simp only [h, if_false]
        have h' : s i < t i := not_le.1 h
        constructor <;> linarith
    · rw [toReal_sub, hq₁real, hzsum, ← Finset.sum_sub_distrib]
      exact Finset.sum_congr rfl fun i _ => by rw [sub_smul]
  · -- `q₁` is a lattice point of `Z`: its coefficients are `0` and `1`.
    refine mem_zonotope_iff.2 ⟨fun i => if t i ≤ s i then (1 : ℝ) else 0, fun i => ?_, hq₁real.symm⟩
    by_cases h : t i ≤ s i <;> simp [h]

/-- The reverse inclusion, which is immediate. -/
theorem sub_lattice_subset {d : Fin m → ℕ} {v : Fin m → ℤ × ℤ}
    {q₀ q₁ : ℤ × ℤ} (h₀ : q₀ ∈ latticePts (zonotope d v)) (h₁ : q₁ ∈ latticePts (zonotope d v)) :
    toReal (q₁ - q₀) ∈ zonotope d v - zonotope d v := by
  rw [toReal_sub]
  exact Set.sub_mem_sub h₁ h₀

/-- The centre-symmetry of a zonotope used in the proof of Lemma 6.1: with
`c₀ = ∑ᵢ dᵢ vᵢ` one has `c₀ - Z = Z`, hence `Z - Z = 2 Z - c₀`. -/
theorem zonotope_centrally_symmetric (d : Fin m → ℕ) (v : Fin m → ℤ × ℤ) :
    (fun x => toReal (∑ i, (d i : ℤ) • v i) - x) '' zonotope d v = zonotope d v := by
  have key : ∀ x ∈ zonotope d v, toReal (∑ i, (d i : ℤ) • v i) - x ∈ zonotope d v := by
    intro x hx
    obtain ⟨c, hc, rfl⟩ := mem_zonotope_iff.1 hx
    refine mem_zonotope_iff.2 ⟨fun i => 1 - c i, fun i => ?_, ?_⟩
    · obtain ⟨h0, h1⟩ := Set.mem_Icc.1 (hc i)
      exact Set.mem_Icc.2 ⟨by linarith, by linarith⟩
    · rw [toReal_sum, ← Finset.sum_sub_distrib]
      exact Finset.sum_congr rfl fun i _ => by rw [sub_smul, one_smul]
  refine Set.Subset.antisymm ?_ fun y hy => ?_
  · rintro y ⟨x, hx, rfl⟩
    exact key x hx
  · exact ⟨_, key y hy, sub_sub_cancel _ _⟩

end Nivat
